#!/usr/bin/env python3

import sys

def factorize(n):
    for i in range(2, n//2 + 1):
        if n % i == 0:
            return i, n//i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        p, q = factorize(n)
        print(f"{n}={p}*{q}")

if __name__ == "__main__":
    main()

